### ISSUE TITLE
EMP towers crash server upon use

### ISSUE THREAD

**Issue by MystcraftMC** [LemADEC/WorldWarMinecraft#15]

**Comment by MystcraftMC** [comment]
When using an EMP directly next to a forcefield with the size range of 40-80, with energy, turned on with both a lever and a button crashed the server. It worked once we got back onto the server, the EMP went through, but it crashed twice while trying it.

**Comment by LemADEC** [comment]
ICBM bug patched server side. WarpDrive needs a workaround for non-patched server.

**Comment by LemADEC** [comment]
WarpDrive workaround added too.
